city: Torrevieja
country: Spain
latitude: 37.9780
longitude: -0.6822
forecast_horizon_days: 3

paths:
  forecasts_raw: data/raw/forecasts
  actuals_raw: data/raw/actuals
  evaluation_processed: data/processed/evaluation
  reports_figures: reports/figures

forecast_providers:
  open-meteo:
    enabled: true

  weatherapi:
    enabled: true
    api_key_env: WEATHERAPI_KEY

  openweathermap:
    enabled: true
    api_key_env: OPENWEATHERMAP_KEY

  visualcrossing:
    enabled: true
    api_key_env: VISUALCROSSING_KEY

  tomorrow:
    enabled: true
    api_key_env: TOMORROW_KEY
